# Generated by Django 4.1.7 on 2023-05-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_clone', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='titile',
            new_name='title',
        ),
    ]
