# Generated by Django 4.2.1 on 2023-06-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_clone', '0005_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
