# Generated by Django 4.1.7 on 2023-07-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_clone', '0006_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='paltform',
            new_name='platform',
        ),
    ]
